lock phpdocumentor/reflection-docblock version 3.1.1
v 3.2.0 cause error

1) BEAR\Resource\InvokerTest::testOptionsMethod
InvalidArgumentException: The tag "@Link(rel="friend",
href="/fiend{?id}")" does not seem to be wellformed, please check it
for errors

https://travis-ci.org/bearsunday/BEAR.Resource/jobs/241904934